[package]
name = "parallel-processes"
version = "0.1.0"
authors = ["Grigorii Efimov <Grigorii_Efimov@epam.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
